apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: kafka
    node: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        node: broker
    spec:
      containers:
      - name: kafka
        image: mattmoore/kafka-broker
        command: ['/docker-entrypoint.sh']
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: '192.168.99.101:30000'
          - name: KAFKA_LISTENERS
            value: 'PLAINTEXT://0.0.0.0:30002'
          - name: KAFKA_ADVERTISED_LISTENERS
            value: 'PLAINTEXT://192.168.99.101:30002'
          - name: KAFKA_BROKER_ID
            value: '0'
        ports:
          - containerPort: 9092
