apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: kafka
    node: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      node: zookeeper
  template:
    metadata:
      labels:
        app: kafka
        node: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: mattmoore/kafka-zookeeper
        command: ['/docker-entrypoint.sh']
        ports:
        - containerPort: 2181
